### ISSUE TITLE
Connecting database and creating schema

### ISSUE THREAD

**Issue by SSais** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-green-cakes#2]
```[tasklist]
### Tasks
- [x] Create a schema using claude
- [x] reset the database
- [x] Once the database has been succesffull do the getmagicalbeasts function
- [x] run the getmagical beast function to ensure the databse has connected
```
